openapi: 3.1.0
info:
  title: LibrePM API
  version: 1.0.0
paths:
  /project:
    get:
      description: Get project list
      responses:
        '200':
          description: List of projects
    post:
      description: Create project
      responses:
        '201':
          description: Created

  /project/{propjectId}:
    get:
      description: Get a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '200':
          description: Project
    put:
      description: Update a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      description: Delete a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /issue:
    get:
      description: Get issue list
      responses:
        '200':
          description: List of issues
    post:
      description: Create issue
      responses:
        '201':
          description: Created
  /issue/{propjectId}:
    get:
      description: Get a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '200':
          description: Issue
    put:
      description: Update a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      description: Delete a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '204':
          description: No content
components:
  Project:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      codeName:
        type: string
      createdAt:
        type: string
  Issue:
    type: object
    properties:
      id:
        type: string
      key:
        type: string
      type:
        type: string
      summary:
        type: string
      description:
        type: string
      status:
        type: string
      createdAt:
        type: string  