openapi: 3.1.0
info:
  title: LibrePM API
  version: 1.0.0
paths:
  /project:
    get:
      tags: ["project"]
      description: Get project list
      responses:
        '200':
          description: List of projects
    post:
      tags: ["project"]
      description: Create project
      responses:
        '201':
          description: Created
  /project/{propjectId}:
    get:
      tags: ["project"]
      description: Get a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '200':
          description: Project
    put:
      tags: ["project"]
      description: Update a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["project"]
      description: Delete a project
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /issue:
    get:
      tags: ["issue"]
      description: Get issue list
      responses:
        '200':
          description: List of issues
    post:
      tags: ["issue"]
      description: Create issue
      responses:
        '201':
          description: Created
  /issue/{issueId}:
    get:
      tags: ["issue"]
      description: Get a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '200':
          description: Issue
    put:
      tags: ["issue"]
      description: Update a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["issue"]
      description: Delete a issue
      parameters:
        - in: path
          name: issueId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /filter:
    get:
      tags: ["filter"]
      description: Get filter list
      responses:
        '200':
          description: List of filters
    post:
      tags: ["filter"]
      description: Create filter
      responses:
        '201':
          description: Created
  /filter/{filterId}:
    get:
      tags: ["filter"]
      description: Get a filter
      parameters:
        - in: path
          name: filterId
          schema:
            type: string
      responses:
        '200':
          description: Filter
    put:
      tags: ["filter"]
      description: Update a filter
      parameters:
        - in: path
          name: filterId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["filter"]
      description: Delete a filter
      parameters:
        - in: path
          name: filterId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /status:
    get:
      tags: ["status"]
      description: Get status list
      responses:
        '200':
          description: List of statuss
    post:
      tags: ["status"]
      description: Create status
      responses:
        '201':
          description: Created
  /status/{statusId}:
    get:
      tags: ["status"]
      description: Get a status
      parameters:
        - in: path
          name: statusId
          schema:
            type: string
      responses:
        '200':
          description: Status
    put:
      tags: ["status"]
      description: Update a status
      parameters:
        - in: path
          name: statusId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["status"]
      description: Delete a status
      parameters:
        - in: path
          name: statusId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /tracker:
    get:
      tags: ["tracker"]
      description: Get tracker list
      responses:
        '200':
          description: List of trackers
    post:
      tags: ["tracker"]
      description: Create tracker
      responses:
        '201':
          description: Created
  /tracker/{trackerId}:
    get:
      tags: ["tracker"]
      description: Get a tracker
      parameters:
        - in: path
          name: trackerId
          schema:
            type: string
      responses:
        '200':
          description: Tracker
    put:
      tags: ["tracker"]
      description: Update a tracker
      parameters:
        - in: path
          name: trackerId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["tracker"]
      description: Delete a tracker
      parameters:
        - in: path
          name: trackerId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /transition:
    get:
      tags: ["transition"]
      description: Get transition list
      responses:
        '200':
          description: List of transitions
    post:
      tags: ["transition"]
      description: Create transition
      responses:
        '201':
          description: Created
  /transition/{transitionId}:
    get:
      tags: ["transition"]
      description: Get a transition
      parameters:
        - in: path
          name: transitionId
          schema:
            type: string
      responses:
        '200':
          description: Transition
    put:
      tags: ["transition"]
      description: Update a transition
      parameters:
        - in: path
          name: transitionId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["transition"]
      description: Delete a transition
      parameters:
        - in: path
          name: transitionId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /board:
    get:
      tags: ["board"]
      description: Get board list
      responses:
        '200':
          description: List of boards
    post:
      tags: ["board"]
      description: Create board
      responses:
        '201':
          description: Created
  /board/{boardId}:
    get:
      tags: ["board"]
      description: Get a board
      parameters:
        - in: path
          name: boardId
          schema:
            type: string
      responses:
        '200':
          description: Board
    put:
      tags: ["board"]
      description: Update a board
      parameters:
        - in: path
          name: boardId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["board"]
      description: Delete a board
      parameters:
        - in: path
          name: boardId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /dashboard:
    get:
      tags: ["dashboard"]
      description: Get dashboard list
      responses:
        '200':
          description: List of dashboards
    post:
      tags: ["dashboard"]
      description: Create dashboard
      responses:
        '201':
          description: Created
  /dashboard/{dashboardId}:
    get:
      tags: ["dashboard"]
      description: Get a dashboard
      parameters:
        - in: path
          name: dashboardId
          schema:
            type: string
      responses:
        '200':
          description: Dashboard
    put:
      tags: ["dashboard"]
      description: Update a dashboard
      parameters:
        - in: path
          name: dashboardId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["dashboard"]
      description: Delete a dashboard
      parameters:
        - in: path
          name: dashboardId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /user:
    get:
      tags: ["user"]
      description: Get user list
      responses:
        '200':
          description: List of users
    post:
      tags: ["user"]
      description: Create user
      responses:
        '201':
          description: Created
  /user/{userId}:
    get:
      tags: ["user"]
      description: Get a user
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: User
    put:
      tags: ["user"]
      description: Update a user
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags: ["user"]
      description: Delete a user
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      responses:
        '204':
          description: No content
  /user/current:
    get:
      tags: ["userCurrent"]
      description: Get current user
      responses:
        '200':
          description: User
    put:
      tags: ["userCurrent"]
      description: Update current user
      responses:
        '200':
          description: User
    delete:
      tags: ["userCurrent"]
      description: Delete current user
      responses:
        '204':
          description: No content
  /user/session:
    post:
      tags: ["userSession"]
      description: Create session
      requestBody:
        content:
          "application/json":
            schema:
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: Session
  /user/register:
    get:
      tags: ["userRegister"]
      description: Register user
      responses:
        '200':
          description: User
    post:
      tags: ["userRegister"]
      description: Register user
      requestBody:
        content:
          "application/json":
            schema:
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: Session
    delete:
      description: Delete session
      responses:
        '204':
          description: No content
components:
  Project:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      codeName:
        type: string
      createdAt:
        type: string
  Issue:
    type: object
    properties:
      id:
        type: string
      key:
        type: string
      type:
        type: string
      summary:
        type: string
      description:
        type: string
      status:
        type: string
      createdAt:
        type: string  
  User:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      language:
        type: string
      country:
        type: string